account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('sign-in/', views.SignIn.as_view(), name='sign_in'),
    path('api/sign-in/', views.ApiSignIn.as_view(), name='api_sign_in'),

    path('sign-out/', views.signout_request, name='sign_out')
]

colors/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('account/', include('account.urls', namespace='account')),
    path('', include('home.urls', namespace='home'))
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('api/color-palletes/all/', views.AllColorPalletesApi.as_view(), name='all_color_palletes_api'),

    #color pallete detail page
    path('<int:id>/', views.ColorDetail.as_view(), name='color_detail'),
    path('api/<int:id>/', views.ColorDetailApi.as_view(), name='color_detail_api'),

    #create color pallete page
    path('create/color/', views.CreateColor.as_view(), name='create_color'),

    #my palletes
    path('dashboard/', views.MyPallete.as_view(), name='my_pallete'),
    path('favourite/', views.Favourite.as_view(), name='favourite'),
    path('favourite/remove/<int:id>/', views.RemoveFavourite.as_view(), name='remove_favourite'),

    #create color pallete api
    path('api/color-pallete/create/', views.ColorPalleteCreateApi.as_view(), name='color_pallete_create_api'),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User


class ColorPallete(models.Model):
    """Color pallete model"""

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=50, null=True, blank=True)

    is_private = models.BooleanField(default=False, null=True, blank=True)

    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.name


class Color(models.Model):
    """Color that associated with color palletes"""

    pallete = models.ForeignKey(ColorPallete, on_delete=models.CASCADE, null=True, blank=True)

    type = models.CharField(max_length=10, null=True, blank=True) #dominant / accent
    color_code = models.CharField(max_length=20, null=True, blank=True)

    def __str__(self):
        return self.pallete.name


class Favourite(models.Model):
    """User favourite color palletes"""

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    pallete = models.ForeignKey(ColorPallete, on_delete=models.CASCADE, null=True, blank=True)

    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.user.username

home/views.py
from django.shortcuts import render, get_object_or_404, redirect, Http404
from django.views import View
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger, Page
from django.db.models import Q

from rest_framework.views import APIView
from rest_framework.generics import ListAPIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.permissions import IsAuthenticated

#import serializer
from . import serializers
from . import paginations

from . import models


class Index(View):
    """Application home page"""

    template_name = 'home/index.html'

    def get(self, request):
        #check user authenticated or not
        if request.user.is_authenticated:
            palletes = models.ColorPallete.objects.all().order_by('-date')
        else:
            palletes = models.ColorPallete.objects.filter(is_private=False).order_by('-date')

        #check if query string exists or not....its for searching
        q = request.GET.get('q')
        if q:
            palletes = palletes.filter(name__icontains=q)

        #count total palletes
        pallete_count = palletes.count()

        #pagnation
        page = request.GET.get('page', 1)
        paginator = Paginator(palletes, 3)

        try:
            palletes = paginator.page(page)
        except PageNotAnInteger:
            palletes = paginator.page(1)
        except EmptyPage:
            palletes = paginator.page(paginator.num_pages)


        index = palletes.number - 1
        max_index = len(paginator.page_range)
        start_index = index - 3 if index >= 3 else 0
        end_index = index + 3 if index <= max_index - 3 else max_index

        page_range = list(paginator.page_range)[start_index:end_index]

        currently_displayed_lower = palletes.start_index()
        currently_displayed_upper = palletes.end_index()
        #end pagination

        variables = {
            'palletes': palletes,
            'pallete_count': pallete_count,
            'page_range': page_range,
            'currently_displayed_lower': currently_displayed_lower,
            'currently_displayed_upper': currently_displayed_upper,
        }
        return render(request, self.template_name, variables)



#all color palletes api
class AllColorPalletesApi(ListAPIView):
    serializer_class = serializers.ColorPalletesSerializers
    pagination_class = paginations.ColorPalletesPagination

    def get_queryset(self):
        if self.request.user.is_authenticated:
            color_palletes = models.ColorPallete.objects.all().order_by('-date')
        else:
            color_palletes = models.ColorPallete.objects.filter(is_private=False).order_by('-date')
        return color_palletes



class CreateColor(View):
    """create color palletes view. color palletes is created using api from that page"""

    template_name = 'home/color/color-pallete-create.html'

    def get(self, request):
        return render(request, self.template_name)



class ColorDetail(View):
    """Color palletes detail page"""

    template_name = 'home/color/color-detail.html'

    def get(self, request, id):
        #get the color palletes using id
        color_pallete = get_object_or_404(models.ColorPallete, id=id)

        #get associated colors
        colors = models.Color.objects.filter(pallete=color_pallete)

        #check color pallets is private and user is not authenticated
        if not request.user.is_authenticated and color_pallete.is_private:
            raise Http404

        #check if requested user has a favourite the color palletes
        check_my_fav = None
        if request.user.is_authenticated:
            check_my_fav = models.Favourite.objects.filter(Q(user=request.user) & Q(pallete=color_pallete)).exists()

        variables = {
            'color_pallete': color_pallete,
            'colors': colors,
            'check_my_fav': check_my_fav
        }
        return render(request, self.template_name, variables)

    def post(self, request, id):
        color_pallete = get_object_or_404(models.ColorPallete, id=id)
        colors = models.Color.objects.filter(pallete=color_pallete)

        #added to favourate list to a user
        if request.POST.get('add_to_fav') == 'add_to_fav':
            add_to_fav = models.Favourite(user=request.user, pallete=color_pallete)
            add_to_fav.save()
            return redirect('home:color_detail', id=id)

        #delete color palletes if he own it
        if request.POST.get('delete') == 'delete':
            if request.user == color_pallete.user:
                color_pallete.delete()
                return redirect('home:index')

        #change color palletes status if he own it
        if request.POST.get('public') == 'public':
            if request.user == color_pallete.user:
                color_pallete.is_private = False
                color_pallete.save()
                return redirect('home:color_detail', id=id)

        #change color palletes status if he own it
        if request.POST.get('private') == 'private':
            if request.user == color_pallete.user:
                color_pallete.is_private = True
                color_pallete.save()
                return redirect('home:color_detail', id=id)

        variables = {
            'color_pallete': color_pallete,
            'colors': colors
        }

        return render(request, self.template_name, variables)




class ColorDetailApi(APIView):
    """color pallete details api"""

    def get(self, request, id):
        #get the color palletes using id
        color_pallete = get_object_or_404(models.ColorPallete, id=id)

        if not request.user.is_authenticated and color_pallete.is_private:
            raise Http404

        #check if requested user has a favourite the color palletes
        check_my_fav = None
        if request.user.is_authenticated:
            check_my_fav = models.Favourite.objects.filter(Q(user=request.user) & Q(pallete=color_pallete)).exists()

        #pallete json
        pallete_dict = {
            "user": color_pallete.user.username,
            "name": color_pallete.name,
            "is_private": color_pallete.is_private
        }

        #get associated colors
        colors = models.Color.objects.filter(pallete=color_pallete)
        colors_json = []
        for color in colors:
            type = color.type
            color_code = color.color_code
            c_dict = {
                "type": type,
                "color_code": color_code
            }
            colors_json.append(c_dict)

        return Response({
            'pallete': pallete_dict,
            'colors': colors_json,
            'favourite': check_my_fav
        }, status=status.HTTP_200_OK)

#=======================================================================================================================
#=======================================================================================================================
#                                                   MY PALLETE
#=======================================================================================================================
#=======================================================================================================================

#permission mixin class for user dashboard
class DashboardPermissionMixin(object):
    def has_permissions(self, request):
        return request.user.is_authenticated

    def dispatch(self, request, *args, **kwargs):
        if not self.has_permissions(request):
            return redirect('home:index')
        return super(DashboardPermissionMixin, self).dispatch(
            request, *args, **kwargs)


#all color palletes create by user
class MyPallete(DashboardPermissionMixin, View):
    template_name = 'home/dashboard/my-pallete.html'

    def get(self, request):
        palletes = models.ColorPallete.objects.filter(user=request.user).order_by('-date')

        pallete_count = palletes.count()

        #pagnation
        page = request.GET.get('page', 1)
        paginator = Paginator(palletes, 3)

        try:
            palletes = paginator.page(page)
        except PageNotAnInteger:
            palletes = paginator.page(1)
        except EmptyPage:
            palletes = paginator.page(paginator.num_pages)


        index = palletes.number - 1
        max_index = len(paginator.page_range)
        start_index = index - 3 if index >= 3 else 0
        end_index = index + 3 if index <= max_index - 3 else max_index

        page_range = list(paginator.page_range)[start_index:end_index]

        currently_displayed_lower = palletes.start_index()
        currently_displayed_upper = palletes.end_index()
        #end pagination

        variables = {
            'palletes': palletes,
            'pallete_count': pallete_count,
            'page_range': page_range,
            'currently_displayed_lower': currently_displayed_lower,
            'currently_displayed_upper': currently_displayed_upper,
        }
        return render(request, self.template_name, variables)


#all favourite add by user
class Favourite(DashboardPermissionMixin, View):
    template_name = 'home/dashboard/favourite.html'

    def get(self, request):
        favs = models.Favourite.objects.filter(user=request.user).order_by('-date')

        favs_count = favs.count()

        #pagnation
        page = request.GET.get('page', 1)
        paginator = Paginator(favs, 3)

        try:
            favs = paginator.page(page)
        except PageNotAnInteger:
            favs = paginator.page(1)
        except EmptyPage:
            favs = paginator.page(paginator.num_pages)


        index = favs.number - 1
        max_index = len(paginator.page_range)
        start_index = index - 3 if index >= 3 else 0
        end_index = index + 3 if index <= max_index - 3 else max_index

        page_range = list(paginator.page_range)[start_index:end_index]

home/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>{% block title %}<!-- title for pages -->{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">

    <style>
        .container{
            min-width: 100%;
        }

        .container > .row {
            margin: 0;
        }


        .container > .row > .col {
            padding: 0;
        }

        *{
            padding: 0px;
            margin: 0px;
            font-family: 'Quicksand', sans-serif;
            font-size: 13px;
        }

        .footer_bottom_link_text a:hover{
            text-decoration: underline;
        }

        .signin_a{
            color: grey;
        }

        .signin_a:hover{
            color: white;
            text-decoration: underline;
        }
    </style>

    {% block style %}
        <!--add css for other individual pages -->
    {% endblock %}

<body>
    <!--nav-->
    <div class="ui stackable grid tablet or lower hidden" style="">
        <div class="sixteen wide column" style="background: #232F3E; padding: 10px;">
            <div class="ui stackable grid" style="">
                <div class="ten wide centered column" style="">


                    <div class="ui secondary mini menu" style="margin-top: 13px;">
                        <a href="{% url 'home:index' %}" class="item" style="color: white; font-size: 17px; font-weight: bold;">
                            COLORS
                        </a>

                        <a href="{% url 'home:index' %}" class="item" style="color: white;">
                            All
                        </a>

                        {% if request.user.is_authenticated %}
                            <a href="{% url 'home:favourite' %}" class="item" style="color: white;">
                                Favourites
                            </a>
                        {% endif %}

                        <div class="right menu">
                            {% if request.user.is_authenticated %}
                                <a href="{% url 'home:my_pallete' %}" class="ui item" style="color: white;">
                                    {{ request.user.username | title }}
                                </a>

                                <a href="{% url 'account:sign_out' %}" class="ui item" style="color: white; margin-right: 10px;">
                                    Sign out
                                </a>
                            {% else %}
                                <a href="{% url 'account:sign_in' %}" class="ui item" style="color: white;">
                                    <i class="user icon"></i>
                                    Sign in
                                </a>
                            {% endif %}

                            {% if request.user.is_authenticated %}
                                <div class="ui item" style="color: white;">
                                    <a href="{% url 'home:create_color' %}" class="ui red button" id="create_color_pallete" style="color: white;">Create color palette</a>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--end nav-->

    {% block body %}
        <!--content for other pages-->
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js"></script>

    {% block script %}
        <!--js for other pages-->
    {% endblock %}
</body>
</html>