account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('sign-in/', views.SignIn.as_view(), name='sign_in'),
    path('api/sign-in/', views.ApiSignIn.as_view(), name='api_sign_in'),

    path('sign-out/', views.signout_request, name='sign_out')
]

colors/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('account/', include('account.urls', namespace='account')),
    path('', include('home.urls', namespace='home'))
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('api/color-palletes/all/', views.AllColorPalletesApi.as_view(), name='all_color_palletes_api'),

    #color pallete detail page
    path('<int:id>/', views.ColorDetail.as_view(), name='color_detail'),
    path('api/<int:id>/', views.ColorDetailApi.as_view(), name='color_detail_api'),

    #create color pallete page
    path('create/color/', views.CreateColor.as_view(), name='create_color'),

    #my palletes
    path('dashboard/', views.MyPallete.as_view(), name='my_pallete'),
    path('favourite/', views.Favourite.as_view(), name='favourite'),
    path('favourite/remove/<int:id>/', views.RemoveFavourite.as_view(), name='remove_favourite'),

    #create color pallete api
    path('api/color-pallete/create/', views.ColorPalleteCreateApi.as_view(), name='color_pallete_create_api'),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User


class ColorPallete(models.Model):
    """Color pallete model"""

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=50, null=True, blank=True)

    is_private = models.BooleanField(default=False, null=True, blank=True)

    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.name


class Color(models.Model):
    """Color that associated with color palletes"""

    pallete = models.ForeignKey(ColorPallete, on_delete=models.CASCADE, null=True, blank=True)

    type = models.CharField(max_length=10, null=True, blank=True) #dominant / accent
    color_code = models.CharField(max_length=20, null=True, blank=True)

    def __str__(self):
        return self.pallete.name


class Favourite(models.Model):
    """User favourite color palletes"""

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    pallete = models.ForeignKey(ColorPallete, on_delete=models.CASCADE, null=True, blank=True)

    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.user.username

home/views.py
from django.shortcuts import render, get_object_or_404, redirect, Http404
from django.views import View
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger, Page
from django.db.models import Q

from rest_framework.views import APIView
from rest_framework.generics import ListAPIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.permissions import IsAuthenticated

#import serializer
from . import serializers
from . import paginations

from . import models


class Index(View):
    """Application home page"""

    template_name = 'home/index.html'

    def get(self, request):
        #check user authenticated or not
        if request.user.is_authenticated:
            palletes = models.ColorPallete.objects.all().order_by('-date')
        else:
            palletes = models.ColorPallete.objects.filter(is_private=False).order_by('-date')

        #check if query string exists or not....its for searching
        q = request.GET.get('q')
        if q:
            palletes = palletes.filter(name__icontains=q)

        #count total palletes
        pallete_count = palletes.count()

        #pagnation
        page = request.GET.get('page', 1)
        paginator = Paginator(palletes, 3)

        try:
            palletes = paginator.page(page)
        except PageNotAnInteger:
            palletes = paginator.page(1)
        except EmptyPage:
            palletes = paginator.page(paginator.num_pages)


        index = palletes.number - 1
        max_index = len(paginator.page_range)
        start_index = index - 3 if index >= 3 else 0
        end_index = index + 3 if index <= max_index - 3 else max_index

        page_range = list(paginator.page_range)[start_index:end_index]

        currently_displayed_lower = palletes.start_index()
        currently_displayed_upper = palletes.end_index()
        #end pagination

        variables = {
            'palletes': palletes,
            'pallete_count': pallete_count,
            'page_range': page_range,
            'currently_displayed_lower': currently_displayed_lower,
            'currently_displayed_upper': currently_displayed_upper,
        }
        return render(request, self.template_name, variables)



#all color palletes api
class AllColorPalletesApi(ListAPIView):
    serializer_class = serializers.ColorPalletesSerializers
    pagination_class = paginations.ColorPalletesPagination

    def get_queryset(self):
        if self.request.user.is_authenticated:
            color_palletes = models.ColorPallete.objects.all().order_by('-date')
        else:
            color_palletes = models.ColorPallete.objects.filter(is_private=False).order_by('-date')
        return color_palletes



class CreateColor(View):
    """create color palletes view. color palletes is created using api from that page"""

    template_name = 'home/color/color-pallete-create.html'

    def get(self, request):
        return render(request, self.template_name)



class ColorDetail(View):
    """Color palletes detail page"""

    template_name = 'home/color/color-detail.html'

    def get(self, request, id):
        #get the color palletes using id
        color_pallete = get_object_or_404(models.ColorPallete, id=id)

        #get associated colors
        colors = models.Color.objects.filter(pallete=color_pallete)

        #check color pallets is private and user is not authenticated
        if not request.user.is_authenticated and color_pallete.is_private:
            raise Http404

        #check if requested user has a favourite the color palletes
        check_my_fav = None
        if request.user.is_authenticated:
            check_my_fav = models.Favourite.objects.filter(Q(user=request.user) & Q(pallete=color_pallete)).exists()

        variables = {
            'color_pallete': color_pallete,
            'colors': colors,
            'check_my_fav': check_my_fav
        }
        return render(request, self.template_name, variables)

    def post(self, request, id):
        color_pallete = get_object_or_404(models.ColorPallete, id=id)
        colors = models.Color.objects.filter(pallete=color_pallete)

        #added to favourate list to a user
        if request.POST.get('add_to_fav') == 'add_to_fav':
            add_to_fav = models.Favourite(user=request.user, pallete=color_pallete)
            add_to_fav.save()
            return redirect('home:color_detail', id=id)

        #delete color palletes if he own it
        if request.POST.get('delete') == 'delete':
            if request.user == color_pallete.user:
                color_pallete.delete()
                return redirect('home:index')

        #change color palletes status if he own it
        if request.POST.get('public') == 'public':
            if request.user == color_pallete.user:
                color_pallete.is_private = False
                color_pallete.save()
                return redirect('home:color_detail', id=id)

        #change color palletes status if he own it
        if request.POST.get('private') == 'private':
            if request.user == color_pallete.user:
                color_pallete.is_private = True
                color_pallete.save()
                return redirect('home:color_detail', id=id)

        variables = {
            'color_pallete': color_pallete,
            'colors': colors
        }

        return render(request, self.template_name, variables)




class ColorDetailApi(APIView):
    """color pallete details api"""

    def get(self, request, id):
        #get the color palletes using id
        color_pallete = get_object_or_404(models.ColorPallete, id=id)

        if not request.user.is_authenticated and color_pallete.is_private:
            raise Http404

        #check if requested user has a favourite the color palletes
        check_my_fav = None
        if request.user.is_authenticated:
            check_my_fav = models.Favourite.objects.filter(Q(user=request.user) & Q(pallete=color_pallete)).exists()

        #pallete json
        pallete_dict = {
            "user": color_pallete.user.username,
            "name": color_pallete.name,
            "is_private": color_pallete.is_private
        }

        #get associated colors
        colors = models.Color.objects.filter(pallete=color_pallete)
        colors_json = []
        for color in colors:
            type = color.type
            color_code = color.color_code
            c_dict = {
                "type": type,
                "color_code": color_code
            }
            colors_json.append(c_dict)

        return Response({
            'pallete': pallete_dict,
            'colors': colors_json,
            'favourite': check_my_fav
        }, status=status.HTTP_200_OK)

#=======================================================================================================================
#=======================================================================================================================
#                                                   MY PALLETE
#=======================================================================================================================
#=======================================================================================================================

#permission mixin class for user dashboard
class DashboardPermissionMixin(object):
    def has_permissions(self, request):
        return request.user.is_authenticated

    def dispatch(self, request, *args, **kwargs):
        if not self.has_permissions(request):
            return redirect('home:index')
        return super(DashboardPermissionMixin, self).dispatch(
            request, *args, **kwargs)


#all color palletes create by user
class MyPallete(DashboardPermissionMixin, View):
    template_name = 'home/dashboard/my-pallete.html'

    def get(self, request):
        palletes = models.ColorPallete.objects.filter(user=request.user).order_by('-date')

        pallete_count = palletes.count()

        #pagnation
        page = request.GET.get('page', 1)
        paginator = Paginator(palletes, 3)

        try:
            palletes = paginator.page(page)
        except PageNotAnInteger:
            palletes = paginator.page(1)
        except EmptyPage:
            palletes = paginator.page(paginator.num_pages)


        index = palletes.number - 1
        max_index = len(paginator.page_range)
        start_index = index - 3 if index >= 3 else 0
        end_index = index + 3 if index <= max_index - 3 else max_index

        page_range = list(paginator.page_range)[start_index:end_index]

        currently_displayed_lower = palletes.start_index()
        currently_displayed_upper = palletes.end_index()
        #end pagination

        variables = {
            'palletes': palletes,
            'pallete_count': pallete_count,
            'page_range': page_range,
            'currently_displayed_lower': currently_displayed_lower,
            'currently_displayed_upper': currently_displayed_upper,
        }
        return render(request, self.template_name, variables)


#all favourite add by user
class Favourite(DashboardPermissionMixin, View):
    template_name = 'home/dashboard/favourite.html'

    def get(self, request):
        favs = models.Favourite.objects.filter(user=request.user).order_by('-date')

        favs_count = favs.count()

        #pagnation
        page = request.GET.get('page', 1)
        paginator = Paginator(favs, 3)

        try:
            favs = paginator.page(page)
        except PageNotAnInteger:
            favs = paginator.page(1)
        except EmptyPage:
            favs = paginator.page(paginator.num_pages)


        index = favs.number - 1
        max_index = len(paginator.page_range)
        start_index = index - 3 if index >= 3 else 0
        end_index = index + 3 if index <= max_index - 3 else max_index

        page_range = list(paginator.page_range)[start_index:end_index]

home/templates/home/color/color-detail.html
{% extends 'base.html' %}

{% block title %}Color pallete details{% endblock %}

{% block body %}
    <div class="ui stackable grid">
        <div class="eight wide centered column" style="margin-top: 30px;">
            <div class="ui segment">
                <form method="post">
                    <h3 style="float: left;">{{ color_pallete.name | upper }}
                        <br /><span style="color: grey;">{{ color_pallete.date | date }}</span>
                    </h3>

                    <p style="float: right">
                        {% csrf_token %}
                        {% if request.user.is_authenticated %}
                            {% if request.user.username != color_pallete.user.username %}
                                {% if not check_my_fav %}
                                    <button name="add_to_fav" value="add_to_fav" class="ui tiny blue icon button">
                                        Add to favorites
                                    </button>
                                {% else %}
                                    <span style="color: red;">This pallete is allready in your favourite list</span>
                                {% endif %}
                            {% else %}
                                <a href="#">Your own</a>
                            {% endif %}
                        {% else %}
                            <a href="{% url 'account:sign_in' %}">Login to add favourate</a>
                        {% endif %}
                    </p>
                    <p style="clear: both"></p>
                    <div class="ui divider"></div>
                </form>

                {% for color in colors %}
                    {{ color.color_code }}
                    <div style="height: 80px; width: 100px; border: 1px solid red; margin-bottom: 10px; background-color: {{ color.color_code }}">
                    </div>
                {% endfor %}

                {% if request.user.username == color_pallete.user.username %}
                    <form method="post">
                        {% csrf_token %}

                        <button type="submit" name="delete" value="delete" class="ui negative button" style="margin-top: 30px;">Delete</button>

                        {% if color_pallete.is_private %}
                            <button type="submit" name="public" value="public" class="ui blue button" style="margin-top: 30px;">Make public</button>
                        {% else %}
                            <button type="submit" name="private" value="private" class="ui blue button" style="margin-top: 30px;">Make private</button>
                        {% endif %}
                    </form>
                {% endif %}

            </div>
        </div>
    </div>
{% endblock %}

{% block script %}

{% endblock %}

home/templates/home/color/color-pallete-create.html
{% extends 'base.html' %}

{% block title %}Create your color pallete{% endblock %}

{% block body %}
    <div class="ui stackable grid">
        <div class="eight wide centered column" style="margin-top: 30px;">
            <div class="ui segment">
                <form class="ui form" method="post" id="color_pallete_form">
                    <h2>Create your color pallete</h2>
                    <div class="ui divider"></div>
                    {% csrf_token %}

                    <div class="field">
                        <label>* Pallete name</label>
                        <input type="text" name="name" placeholder="Color pallete name">

                        <div id="name_err_msg" style="margin-top: 10px; margin-bottom: 20px;">

                        </div>
                    </div>

                    <div class="field" style="margin-top: 20px;">
                        <label>* Dominent color (max 2)</label>

                        <div id="dominent_fields">

                        </div>

                        <button type="button" class="ui mini icon button add_dominent">
                            <i class="plus icon"></i>
                        </button>

                        <div id="dominant_err_msg" style="margin-top: 10px; margin-bottom: 20px;">

                        </div>
                    </div>

                    <div class="field" style="margin-top: 20px;">
                        <label>* Accent color (max 4)</label>

                        <div id="accent_fields">

                        </div>

                        <button type="button" class="ui mini icon button add_accent">
                            <i class="plus icon"></i>
                        </button>

                        <div id="accent_err_msg" style="margin-top: 10px; margin-bottom: 20px;">

                        </div>
                    </div>

                    <div class="inline field">
                        <div class="ui toggle checkbox">
                            <input type="checkbox" name="status" class="hidden">
                            <label>Private</label>
                        </div>
                    </div>

                    <button type="submit" class="ui blue button">Create</button>

                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
        $('.ui.checkbox').checkbox();

        var addDominent = $('.add_dominent');

        var field_html = '\
            <div class="two fields dominent_input">\
                \
                <div class="field" style="margin-bottom: 10px;">\
                    <input type="color" name="dominentcolor">\
                </div>\
                \
                <button type="button" class="ui positive mini button remove_button">\
                    remove\
                </button> \
                \
                \
            </div>\
        ';

        $(addDominent).click(function(){
            $('#dominent_fields').append(field_html);
        });

        $("#dominent_fields").on('click', '.remove_button', function(e){
            e.preventDefault();
            $(this).parent('.dominent_input').remove();
        });


        //accent color js
        var addAccent = $('.add_accent');

        var field_html_accent = '\
            <div class="two fields accent_input">\
                \
                <div class="field" style="margin-bottom: 10px;">\
                    <input type="color" name="accentcolor">\
                </div>\
                \
                <button type="button" class="ui positive mini button remove_button">\
                    remove\
                </button> \
                \
                \
            </div>\
        ';

        $(addAccent).click(function(){
            $('#accent_fields').append(field_html_accent);
        });

        $("#accent_fields").on('click', '.remove_button', function(e){
            e.preventDefault();
            $(this).parent('.accent_input').remove();
        });
    </script>

    <script>

        function validate_form(name, dominent_color_counter, accent_color_counter){
            if(name.length < 1){
                err_msg = '* Enter name!';
                html = '\
					<div class="ui red message">\
						'+ err_msg +'\
					</div>\
                ';
                $("#name_err_msg").html(' ');
                $("#name_err_msg").append(html);
                return false;
            }else if(name.length > 50){
                err_msg = '* Name cant be more than 50 characters!';
                html = '\
					<div class="ui red message">\
						'+ err_msg +'\
					</div>\
                ';
                $("#name_err_msg").html(' ');
                $("#name_err_msg").append(html);
                return false;
            }else if(dominent_color_counter < 1){
                err_msg = '* Add atleast 1 dominent color!';
                html = '\
					<div class="ui red message">\
						'+ err_msg +'\
					</div>\
                ';
                $("#dominant_err_msg").html(' ');
                $("#dominant_err_msg").append(html);
                return false;
            }else if(dominent_color_counter > 2){
                err_msg = '* You cant add more than 2 dominent color!';
                html = '\
					<div class="ui red message">\
						'+ err_msg +'\
					</div>\
                ';
                $("#dominant_err_msg").html(' ');
                $("#dominant_err_msg").append(html);
                return false;
            }else if(accent_color_counter < 1){
                err_msg = '* Add atleast 1 accent color!';
                html = '\
					<div class="ui red message">\
						'+ err_msg +'\
					</div>\
                ';
                $("#accent_err_msg").html(' ');
                $("#accent_err_msg").append(html);
                return false;
            }else if(accent_color_counter > 4){
                err_msg = '* You cant add more than 4 accent color!';
                html = '\
					<div class="ui red message">\
						'+ err_msg +'\
					</div>\
                ';
                $("#accent_err_msg").html(' ');
                $("#accent_err_msg").append(html);
                return false;
            }else{
                return true;
            }
        }

        $("#color_pallete_form").submit(function(e){
            e.preventDefault();
            name = $("input[name=name]").val();

            if ($("input[name=status]").is(":checked")){
                //true means private
                status = true
            }else{
                status = false
            }


            dominent_color_counter = $("input[name=dominentcolor]").length;
            accent_color_counter = $("input[name=accentcolor]").length;

            dominent_color = $("input[name=dominentcolor]").map(function(){ return {"type": "dominent", "code": $(this).val()} }).get();
            accent_color = $("input[name=accentcolor]").map(function(){ return {"type": "accent", "code": $(this).val()} }).get();

            validate = validate_form(name, dominent_color_counter, accent_color_counter);

            if(validate){
                colors = $.merge(dominent_color, accent_color);
                colors_json = JSON.stringify(colors)
                $.ajax({
                    url: '{% url 'home:color_pallete_create_api' %}',
                    data: {"name": name, "is_private": status, "colors": colors_json, "csrfmiddlewaretoken": "{{ csrf_token }}"},
                    type: 'post',
                    dataType: 'json',
                    success: function (data){
                        location.href = '/'
                    },
                    error: function (jqXHR, exception) {
                        if (jqXHR.status == 404) {
                            console.log("404 not found!");
                        }
                        console.log(jqXHR)
                    }
                });

            }
        });
    </script>
{% endblock %}